//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSTA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class komentar
    {
        public int IDkomentar { get; set; }
        public string IDobjava { get; set; }
        public Nullable<int> IDlike { get; set; }
        public string IDkorisnicko_ime { get; set; }
        public string komentar1 { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
    
        public virtual objava objava { get; set; }
    }
}
