//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSTA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public objava()
        {
            this.komentars = new HashSet<komentar>();
            this.lajks = new HashSet<lajk>();
        }
    
        public string IDobjava { get; set; }
        public string IDkorisnicko_ime { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string opis { get; set; }
        public Nullable<int> total_like { get; set; }
        public Nullable<int> total_coment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<komentar> komentars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lajk> lajks { get; set; }
        public virtual profil profil { get; set; }
    }
}
