//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSTA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poklon_za_profil
    {
        public int ID_poklon_za_profil { get; set; }
        public Nullable<int> ID_poklon { get; set; }
        public string ID_korisnicko_ime { get; set; }
    
        public virtual poklon poklon { get; set; }
        public virtual profil profil { get; set; }
    }
}
