//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSTA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profil()
        {
            this.objavas = new HashSet<objava>();
            this.poklon_za_profil = new HashSet<poklon_za_profil>();
        }
    
        public string IDkorisnicko_ime { get; set; }
        public Nullable<int> IDkategorija { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string pol { get; set; }
        public string telefon { get; set; }
        public Nullable<int> broj_pratilaca { get; set; }
        public Nullable<System.DateTime> datum_rodjenja { get; set; }
    
        public virtual kategorija kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objava> objavas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poklon_za_profil> poklon_za_profil { get; set; }
    }
}
